import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { extname, join, basename } from 'node:path';

export interface ExtractRecord {
  source: string;          // input filename (basename, e.g. "report.pdf")
  output?: string;         // output filename in _extracted/ (e.g. "report.md")
  reason?: string;         // skip reason or extraction note
  bytes?: number;          // output size
}

export interface ExtractResult {
  extracted: ExtractRecord[];
  skipped: ExtractRecord[];
}

export interface ExtractInput {
  repoRoot: string;
  slug: string;
  /** Optional parser override for tests; defaults to the officeparser lib. */
  parseOfficeAsync?: (path: string) => Promise<string>;
}

const SUPPORTED = new Set(['.pdf', '.pptx', '.docx', '.md', '.txt']);
const OFFICE = new Set(['.pdf', '.pptx', '.docx']);

export function shouldExtract(name: string): boolean {
  return SUPPORTED.has(extname(name).toLowerCase());
}

export function basenameForOutput(name: string): string {
  const ext = extname(name);
  return basename(name, ext);
}

/**
 * Walk `slides/<slug>/references/` (non-recursive), extract supported files
 * to `references/_extracted/<basename>.md`, and write an `_index.md` manifest.
 * PDF / PPTX / DOCX are parsed via officeparser. MD files are passed through
 * verbatim (preserving any original frontmatter). TXT files are wrapped in
 * a minimal markdown header.
 *
 * @param input.parseOfficeAsync — test-only override for the office parser.
 */
export async function extractReferences(input: ExtractInput): Promise<ExtractResult> {
  const refsDir = join(input.repoRoot, 'slides', input.slug, 'references');
  if (!existsSync(refsDir)) {
    return { extracted: [], skipped: [] };
  }

  const outDir = join(refsDir, '_extracted');
  const parseOffice = input.parseOfficeAsync ?? defaultOfficeParser;

  const extracted: ExtractRecord[] = [];
  const skipped: ExtractRecord[] = [];

  const entries = readdirSync(refsDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    if (entry.name.startsWith('_')) continue; // skip _extracted dir and other leading-underscore files
    if (!shouldExtract(entry.name)) {
      skipped.push({ source: entry.name, reason: `unsupported extension ${extname(entry.name)}` });
      continue;
    }

    const srcPath = join(refsDir, entry.name);
    const ext = extname(entry.name).toLowerCase();
    const outName = basenameForOutput(entry.name) + '.md';
    const outPath = join(outDir, outName);
    mkdirSync(outDir, { recursive: true });

    try {
      if (ext === '.md') {
        writeFileSync(outPath, readFileSync(srcPath, 'utf8'));
      } else if (ext === '.txt') {
        const raw = readFileSync(srcPath, 'utf8');
        writeFileSync(outPath, `# ${basenameForOutput(entry.name)}\n\n${raw}\n`);
      } else if (OFFICE.has(ext)) {
        const raw = await parseOffice(srcPath);
        // officeparser v6+ returns a structured node tree; older versions and test
        // injections may return a plain string. Normalize both into markdown-ish text.
        const text = typeof raw === 'string' ? raw : flattenOfficeTree(raw as unknown as OfficeNode);
        const header = `# ${basenameForOutput(entry.name)}\n\n_Source: ${entry.name}_\n\n`;
        writeFileSync(outPath, header + text.trim() + '\n');
      }
      const bytes = readFileSync(outPath).byteLength;
      extracted.push({ source: entry.name, output: outName, bytes });
    } catch (err) {
      skipped.push({ source: entry.name, reason: `parse error: ${(err as Error).message}` });
    }
  }

  if (extracted.length > 0) {
    const index =
      `# Extracted references\n\n` +
      `_Auto-generated by \`pnpm extract-refs --slug ${input.slug}\` — regenerate anytime; do not edit by hand._\n\n` +
      extracted
        .map((e) =>
          e.source === e.output
            ? `- [${e.source}](${e.output})`
            : `- [${e.source} → ${e.output}](${e.output})`,
        )
        .join('\n') +
      '\n';
    writeFileSync(join(outDir, '_index.md'), index);
  }

  return { extracted, skipped };
}

interface OfficeNode {
  type?: string;
  text?: string;
  children?: OfficeNode[];
  content?: OfficeNode[];
}

/** Walk the structured officeparser v6 tree and concatenate all leaf text. */
function flattenOfficeTree(node: OfficeNode | OfficeNode[] | string | undefined): string {
  if (!node) return '';
  if (typeof node === 'string') return node;
  if (Array.isArray(node)) return node.map(flattenOfficeTree).join('\n');

  const parts: string[] = [];
  // Prefer a paragraph's own .text (full line) over walking its children's .text
  // (which may split the same line across multiple leaf nodes).
  if (node.type === 'paragraph' && typeof node.text === 'string') {
    parts.push(node.text);
  } else {
    if (typeof node.text === 'string') parts.push(node.text);
    if (node.children) parts.push(flattenOfficeTree(node.children));
  }
  if (node.content) parts.push(flattenOfficeTree(node.content));
  return parts.filter(Boolean).join(node.type === 'page' || node.type === 'slide' ? '\n\n' : '\n');
}

async function defaultOfficeParser(path: string): Promise<string> {
  // Deferred import so tests can run without the heavy dep loaded;
  // officeparser is present as a direct dep for production use.
  const mod = await import('officeparser');
  const parse = (mod as unknown as { parseOffice: (p: string) => Promise<OfficeNode | string> }).parseOffice;
  const result = await parse(path);
  // Normalization of v6's structured output also happens at the call site, but we
  // keep it here so direct users of defaultOfficeParser still get a string.
  return typeof result === 'string' ? result : flattenOfficeTree(result);
}
